#! /usr/bin/env perl
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
#
# Copyright © 2015 Adrian Perez <aperez@igalia.com>
#
# Distributed under terms of the MIT license.

use strict;
use warnings;
use Gtk3 -init;
use Glib::Object::Introspection ();
Glib::Object::Introspection->setup(
    basename => 'WebKit2',
    version  => '4.0',
    package  => 'WebKit2',
);
use FindBin ();

my $mydir = $FindBin::Bin;
print "Extension directory: ", $mydir, "\n";

my $ctx = WebKit2::WebContext::get_default();
$ctx->set_web_extensions_directory($mydir);
$ENV{PLWKEXT} = "$FindBin::Bin/extension.pl";

my $wnd = Gtk3::Window->new();
my $web = WebKit2::WebView->new_with_context($ctx);
$wnd->signal_connect(destroy => \&Gtk3::main_quit);
$wnd->add($web);
$wnd->set_default_size(1152, 800);
$wnd->show_all();

if(@ARGV > 0) {
    $web->load_uri($ARGV[0]);
} else {
    $web->load_uri('http://ddg.gg');
}

Gtk3::main();
